---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 3000  
eureka:
  instance:
    hostname: localhost  
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    

# java -jar -Dspring.profiles.active=tertiary lab-4-eureka-server-solution-0.0.1-SNAPSHOT.jar

---
spring:
  profiles: primary
server:
  port: 8011  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: secondary
server:
  port: 8012  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8013/eureka/,http://localhost:8011/eureka/

---
spring:
  profiles: tertiary
server:
  port: 8013  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/
      