# Note: all properties defined in this file are subject to replacement by the configuration server.
---
words: fallback
lucky-world: fallback
---
spring:
  profiles: cold-noun
words: icicle,refrigerator,blizzard,snowball